/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NSpace: typeof import('naive-ui')['NSpace']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
